# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux Build, Test, Release Python Packge

on: [push, pull_request]

jobs:
  build:
    name: Install and Test 🐍
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ['3.6', '3.7']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: gldas
          auto-activate-base: false
      - name: Print environment infos
        shell: bash -l {0}
        run: |
          conda info -a
          conda list
          pip list
          which pip
          which python
      - name: Install package
        shell: bash -l {0}
        run: |
          python setup.py install
      - name: Run setup.py test
        shell: bash -l {0}
        run: |
          python setup.py test
      - name: Upload Coverage
        shell: bash -l {0}
        run: |
          pip install coveralls && coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
  coveralls:
    name: Submit Coveralls 👚
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls && coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Create Package Release 📦
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        # id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./CHANGELOG.rst
          draft: false
          prerelease: false
  publish:
    name: Upload to Pypi 🚀
    needs: release
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - uses: actions/checkout@v2
      - name: distribution
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py sdist # bdist_wheel
      - name: Publish distribution to Test PyPI
        # if: startsWith(github.ref, 'refs/tags') # todo: add for safety for real pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }} # todo: change token for real pypi
          repository_url: https://test.pypi.org/legacy/ # todo: drop line to publish to real pyp